# Generated by Django 4.2.13 on 2024-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                (
                    "book_type",
                    models.CharField(
                        choices=[
                            ("paperback", "Paperback"),
                            ("hardcover", "Hardcover"),
                            ("handmade", "Handmade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("owl_id", models.CharField(max_length=50, unique=True)),
                ("available", models.BooleanField(default=True)),
                ("borrowed_at", models.DateField(blank=True, null=True)),
                ("returned_at", models.DateField(blank=True, null=True)),
                (
                    "borrower_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
    ]
